<a href="https://colab.research.google.com/github/hyounghe0724/StartPytorch/blob/main/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# loss function의 최솟값을 구하는 목표

In [ ]:
import torch

x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


**자동 미분**

In [ ]:
y = x + 1

In [ ]:
z = 2*y**2
res = z.mean() # 평균
print("y=", y)
print("z=", z)
print("Result = ", res)
#grad_fn 은 추적이 잘 되고 있다는 의미

y= tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
z= tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)
Result =  tensor(8., grad_fn=<MeanBackward0>)


**역전파**

In [ ]:
res.backward() # 기준을 정해주어야함, res를 기준으로 역전파를 진행

# res = (z11 + z12 + ..) /4
# z_i = 2 y_i ** 2
# z_i = 2 (x_i+1) ** 2
# d(res)/dx_i = x_i + 1

In [ ]:
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]])
