<a href="https://colab.research.google.com/github/hyounghe0724/StartPytorch/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [2]:
# 빈 텐서 생성
x = torch.empty(5,4) # 5 by 4
print(x) # 초기화 되지 않으면 랜덤 값

tensor([[7.1450e-13, 4.3394e-41, 7.1450e-13, 4.3394e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.3631e-44, 1.5766e-19, 3.0725e-18, 4.3394e-41],
        [1.4013e-45, 0.0000e+00, 2.8026e-45, 1.4013e-45],
        [2.8026e-45, 5.6052e-45, 2.8026e-45, 1.2612e-44]])


In [3]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2)

tensor([0., 0.])

In [5]:
torch.rand(5,6)

tensor([[0.5560, 0.8059, 0.6717, 0.8009, 0.2450, 0.1663],
        [0.5830, 0.2677, 0.1063, 0.2245, 0.3831, 0.9669],
        [0.8449, 0.8799, 0.5951, 0.3128, 0.8708, 0.9397],
        [0.8126, 0.0088, 0.4005, 0.5880, 0.8457, 0.8992],
        [0.4126, 0.5893, 0.4768, 0.4305, 0.5286, 0.9836]])

In [6]:
l = [13,4]
r = np.array([4,56,7])

torch.tensor(l)

tensor([13,  4])

In [7]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [11]:
torch.FloatTensor(r)

tensor([ 4., 56.,  7.])

In [21]:
x.size()

torch.Size([5, 4])

In [22]:
print(x.shape)


torch.Size([5, 4])


In [23]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)


tensor([[0.3727, 0.2354],
        [0.2172, 0.9224]])
tensor([[0.3952, 0.1766],
        [0.5207, 0.3768]])


In [24]:
x+y

tensor([[0.7680, 0.4120],
        [0.7378, 1.2992]])

In [25]:
torch.add(x,y)

tensor([[0.7680, 0.4120],
        [0.7378, 1.2992]])

In [26]:
y.add(x)

tensor([[0.7680, 0.4120],
        [0.7378, 1.2992]])

In [27]:
# y.add_(x) => y = y + x  inplace 방식

In [32]:
x = torch.rand(8,8)
x
print(x.size())

torch.Size([8, 8])


In [34]:
a = x.view(64)
print(a)
a.shape

tensor([0.7248, 0.3994, 0.6343, 0.4381, 0.1002, 0.5859, 0.4027, 0.8647, 0.2735,
        0.7656, 0.2086, 0.3081, 0.8099, 0.5897, 0.0094, 0.7705, 0.9202, 0.1921,
        0.9342, 0.4766, 0.1257, 0.3754, 0.9993, 0.8255, 0.6832, 0.6648, 0.8283,
        0.8146, 0.6561, 0.8298, 0.3875, 0.2461, 0.2253, 0.0514, 0.1835, 0.7604,
        0.8801, 0.9880, 0.2077, 0.9987, 0.0202, 0.9781, 0.5480, 0.5478, 0.4344,
        0.8494, 0.8341, 0.1399, 0.2135, 0.1678, 0.9701, 0.9871, 0.6350, 0.1533,
        0.0577, 0.1111, 0.8242, 0.5191, 0.1819, 0.5396, 0.9496, 0.7812, 0.9326,
        0.9096])


torch.Size([64])

In [35]:
b = x.view(-1, 4,4) # -1은 원래 크기가 되게 하는 값 8by8 -> -1by4by4 즉, 444이다
# 4 by 4를 채우고 나머지는 원래의 값을 알맞게 자동으로 채워줌
print(b.size())
print(b)

torch.Size([4, 4, 4])
tensor([[[0.7248, 0.3994, 0.6343, 0.4381],
         [0.1002, 0.5859, 0.4027, 0.8647],
         [0.2735, 0.7656, 0.2086, 0.3081],
         [0.8099, 0.5897, 0.0094, 0.7705]],

        [[0.9202, 0.1921, 0.9342, 0.4766],
         [0.1257, 0.3754, 0.9993, 0.8255],
         [0.6832, 0.6648, 0.8283, 0.8146],
         [0.6561, 0.8298, 0.3875, 0.2461]],

        [[0.2253, 0.0514, 0.1835, 0.7604],
         [0.8801, 0.9880, 0.2077, 0.9987],
         [0.0202, 0.9781, 0.5480, 0.5478],
         [0.4344, 0.8494, 0.8341, 0.1399]],

        [[0.2135, 0.1678, 0.9701, 0.9871],
         [0.6350, 0.1533, 0.0577, 0.1111],
         [0.8242, 0.5191, 0.1819, 0.5396],
         [0.9496, 0.7812, 0.9326, 0.9096]]])


In [37]:
x = torch.rand(8,8)
y = x.numpy()
print(y)
type(y)

[[1.5081906e-01 7.8949416e-01 9.8189801e-01 3.4242272e-03 1.6137815e-01
  2.3695159e-01 3.4994793e-01 6.9549686e-01]
 [2.0519906e-01 5.6955636e-01 8.4937084e-01 5.1737863e-01 5.9120387e-01
  6.0125160e-01 2.7293456e-01 3.8968652e-01]
 [8.3305633e-01 4.3830746e-01 9.2330199e-01 9.1320562e-01 7.1404713e-01
  9.4538212e-01 2.8892595e-01 6.3356107e-01]
 [4.7501463e-01 7.6059210e-01 5.7166398e-02 6.7555737e-01 2.5100464e-01
  4.4222027e-01 3.0639768e-01 8.3496732e-01]
 [5.8414936e-01 5.4767162e-01 5.8557248e-01 4.0945429e-01 4.8458576e-04
  8.0770612e-01 3.7750840e-02 5.9383351e-01]
 [1.7811775e-01 7.9067242e-01 7.0757610e-01 3.1197250e-02 5.3138274e-01
  5.7303023e-01 2.1320832e-01 9.2719328e-01]
 [4.8100841e-01 5.0542390e-01 1.2576640e-02 8.4487373e-01 6.7338347e-01
  9.6671140e-01 1.3048905e-01 1.7401153e-01]
 [7.1321404e-01 6.3329536e-01 1.5040272e-01 3.7442535e-01 7.9128492e-01
  1.0136646e-01 4.8757982e-01 1.3775378e-01]]


numpy.ndarray

In [38]:
loss = torch.ones(1)

In [40]:
print(loss)
print(loss.item()) # 값만  보ㄹ여 줄 수 있다

tensor([1.])
1.0
